# Basic Site Settings
locale                   : "en-US"
site_theme               : "minimal" # Changed from default to minimal
title                    : "Aliaksandr Babich"
title_separator          : "-"
name                     : "Aliaksandr Babich"
description              : "Personal academic website"
repository               : "mrdocror/mrdocror.github.io"
url                      : https://mrdocror.github.io
baseurl                  : ""

# Site Author
author:
  avatar           : "profile.png"
  name             : "Aliaksandr Babich"
  bio              : # Add your bio here if desired
  location         : # Add your location if desired
  employer         : "Virginia Tech"
  email            : "aliaksandr2004@gmail.com"
  github           : "mrdocror"
  linkedin         : "Aliaksandr Babich"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github