# Basic Site Settings
locale                   : "en-US"
site_theme               : "minimal"
title                    : "Aliaksandr Babich"
title_separator          : "-"
name                     : "Aliaksandr Babich"
description              : "Personal website"
repository               : "mrdocror/mrdocror.github.io"
url                      : https://mrdocror.github.io
baseurl                  : ""

# Site Author
author:
  avatar           : "profile.png"
  name             : "Aliaksandr Babich"
  bio              : # Add your bio here if desired
  location         : # Add your location if desired
  employer         : "Virginia Tech"
  email            : "aliaksandr2004@gmail.com"
  github           : "mrdocror"
  linkedin         : "Aliaksandr Babich"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  guides:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
  # _guides
  - scope:
      path: ""
      type: guides
    values:
      layout: single
      author_profile: true

# Navigation
main_nav:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Guides"
    url: /guides/

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github